apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- rbac.yaml
- vault.yaml
- services.yaml
- vault-auth.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize