apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- crd.yaml
- rbac.yaml
- kubegres.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
