apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  namespace: default
spec:
  serviceAccountName: vault-auth
  containers:
  - name: python
    image: python:3.9.20
    workingDir: /app
    command:
    - bash
    - -c
    - "pip install -r requirements.txt; python -m app.auth"
    env:
      - name: VAULT_URL
        value: http://vault.vault.svc.cluster.local:8200
    volumeMounts:
    - name: app
      mountPath: /app
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  volumes:
  - name: app
    hostPath:
      path: /app
  - name: vault-token
    projected:
      sources:
        - serviceAccountToken:
            path: vault
            audience: vault
            expirationSeconds: 900
