apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    replicationRole: primary
  name: pg-nodeport
  namespace: default
spec:
  type: NodePort
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  ports:
  - port: 5433
    targetPort: 5432
    nodePort: 30021
  selector:
    app: postgres
    replicationRole: primary
